# Generated by Django 5.0 on 2026-04-12 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='aliment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='nutrition.aliment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lot',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='nutrition.produit'),
        ),
    ]
