# Generated by Django 5.0 on 2026-04-08 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_foyer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('calories', models.FloatField()),
                ('proteines', models.FloatField()),
                ('glucides', models.FloatField()),
                ('lipides', models.FloatField()),
                ('fibres', models.FloatField()),
                ('quantite_reference', models.FloatField(default=100)),
                ('unite_reference', models.CharField(default='g', max_length=10)),
                ('off_id', models.CharField(blank=True, max_length=100, null=True)),
                ('derniere_utilisation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliments_crees', to=settings.AUTH_USER_MODEL)),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliments', to='auth_foyer.foyer')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliments', to='nutrition.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Micros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('valeur', models.FloatField()),
                ('unite', models.CharField(max_length=10)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micros', to='nutrition.aliment')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commercial', models.CharField(max_length=255)),
                ('poids_reference', models.FloatField()),
                ('prix', models.FloatField(blank=True, null=True)),
                ('code_barre', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='nutrition.aliment')),
            ],
        ),
    ]
