# Generated by Django 5.0 on 2026-04-08 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_foyer', '0001_initial'),
        ('inventory', '0001_initial'),
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('courses_en_cours', 'Courses en cours')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listes_courses', to='auth_foyer.foyer')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_libre', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.FloatField(blank=True, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aliment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_courses', to='nutrition.aliment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_courses_creees', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_courses', to='inventory.lot')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_courses', to='nutrition.produit')),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='shopping.listecourses')),
            ],
        ),
    ]
