# Generated by Django 5.0 on 2026-04-08 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_foyer', '0001_initial'),
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='auth_foyer.foyer')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repas', to='planning.moment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'moment')},
            },
        ),
        migrations.CreateModel(
            name='LigneRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
                ('calories_snapshot', models.FloatField()),
                ('proteines_snapshot', models.FloatField()),
                ('glucides_snapshot', models.FloatField()),
                ('lipides_snapshot', models.FloatField()),
                ('fibres_snapshot', models.FloatField()),
                ('prix_snapshot', models.FloatField(blank=True, null=True)),
                ('lot_peremption_snapshot', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_repas', to='nutrition.aliment')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='planning.repas')),
            ],
        ),
    ]
