# Generated by Django 5.0 on 2026-04-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignerepas',
            old_name='planning',
            new_name='repas',
        ),
    ]
